#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAESGenome.Console
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="cgf")]
	public partial class DataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBarcodeFile(BarcodeFile instance);
    partial void UpdateBarcodeFile(BarcodeFile instance);
    partial void DeleteBarcodeFile(BarcodeFile instance);
    partial void InsertBarcode(Barcode instance);
    partial void UpdateBarcode(Barcode instance);
    partial void DeleteBarcode(Barcode instance);
    #endregion
		
		public DataDataContext() : 
				base(global::CAESGenome.Console.Properties.Settings.Default.cgfConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<BarcodeFile> BarcodeFiles
		{
			get
			{
				return this.GetTable<BarcodeFile>();
			}
		}
		
		public System.Data.Linq.Table<Barcode> Barcodes
		{
			get
			{
				return this.GetTable<Barcode>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BarcodeFiles")]
	public partial class BarcodeFile : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _WellColumn;
		
		private char _WellRow;
		
		private int _BarcodeId;
		
		private bool _Uploaded;
		
		private bool _Validated;
		
		private System.Nullable<int> _Start;
		
		private System.Nullable<int> _End;
		
		private System.DateTime _DateTimeUploaded;
		
		private System.Nullable<System.DateTime> _DateTimeValidated;
		
		private EntityRef<Barcode> _Barcode;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnWellColumnChanging(int value);
    partial void OnWellColumnChanged();
    partial void OnWellRowChanging(char value);
    partial void OnWellRowChanged();
    partial void OnBarcodeIdChanging(int value);
    partial void OnBarcodeIdChanged();
    partial void OnUploadedChanging(bool value);
    partial void OnUploadedChanged();
    partial void OnValidatedChanging(bool value);
    partial void OnValidatedChanged();
    partial void OnStartChanging(System.Nullable<int> value);
    partial void OnStartChanged();
    partial void OnEndChanging(System.Nullable<int> value);
    partial void OnEndChanged();
    partial void OnDateTimeUploadedChanging(System.DateTime value);
    partial void OnDateTimeUploadedChanged();
    partial void OnDateTimeValidatedChanging(System.Nullable<System.DateTime> value);
    partial void OnDateTimeValidatedChanged();
    #endregion
		
		public BarcodeFile()
		{
			this._Barcode = default(EntityRef<Barcode>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WellColumn", DbType="Int NOT NULL")]
		public int WellColumn
		{
			get
			{
				return this._WellColumn;
			}
			set
			{
				if ((this._WellColumn != value))
				{
					this.OnWellColumnChanging(value);
					this.SendPropertyChanging();
					this._WellColumn = value;
					this.SendPropertyChanged("WellColumn");
					this.OnWellColumnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WellRow", DbType="Char(1) NOT NULL")]
		public char WellRow
		{
			get
			{
				return this._WellRow;
			}
			set
			{
				if ((this._WellRow != value))
				{
					this.OnWellRowChanging(value);
					this.SendPropertyChanging();
					this._WellRow = value;
					this.SendPropertyChanged("WellRow");
					this.OnWellRowChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BarcodeId", DbType="Int NOT NULL")]
		public int BarcodeId
		{
			get
			{
				return this._BarcodeId;
			}
			set
			{
				if ((this._BarcodeId != value))
				{
					if (this._Barcode.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnBarcodeIdChanging(value);
					this.SendPropertyChanging();
					this._BarcodeId = value;
					this.SendPropertyChanged("BarcodeId");
					this.OnBarcodeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Uploaded", DbType="Bit NOT NULL")]
		public bool Uploaded
		{
			get
			{
				return this._Uploaded;
			}
			set
			{
				if ((this._Uploaded != value))
				{
					this.OnUploadedChanging(value);
					this.SendPropertyChanging();
					this._Uploaded = value;
					this.SendPropertyChanged("Uploaded");
					this.OnUploadedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Validated", DbType="Bit NOT NULL")]
		public bool Validated
		{
			get
			{
				return this._Validated;
			}
			set
			{
				if ((this._Validated != value))
				{
					this.OnValidatedChanging(value);
					this.SendPropertyChanging();
					this._Validated = value;
					this.SendPropertyChanged("Validated");
					this.OnValidatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Start", DbType="Int")]
		public System.Nullable<int> Start
		{
			get
			{
				return this._Start;
			}
			set
			{
				if ((this._Start != value))
				{
					this.OnStartChanging(value);
					this.SendPropertyChanging();
					this._Start = value;
					this.SendPropertyChanged("Start");
					this.OnStartChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[End]", Storage="_End", DbType="Int")]
		public System.Nullable<int> End
		{
			get
			{
				return this._End;
			}
			set
			{
				if ((this._End != value))
				{
					this.OnEndChanging(value);
					this.SendPropertyChanging();
					this._End = value;
					this.SendPropertyChanged("End");
					this.OnEndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateTimeUploaded", DbType="DateTime2 NOT NULL")]
		public System.DateTime DateTimeUploaded
		{
			get
			{
				return this._DateTimeUploaded;
			}
			set
			{
				if ((this._DateTimeUploaded != value))
				{
					this.OnDateTimeUploadedChanging(value);
					this.SendPropertyChanging();
					this._DateTimeUploaded = value;
					this.SendPropertyChanged("DateTimeUploaded");
					this.OnDateTimeUploadedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateTimeValidated", DbType="DateTime2")]
		public System.Nullable<System.DateTime> DateTimeValidated
		{
			get
			{
				return this._DateTimeValidated;
			}
			set
			{
				if ((this._DateTimeValidated != value))
				{
					this.OnDateTimeValidatedChanging(value);
					this.SendPropertyChanging();
					this._DateTimeValidated = value;
					this.SendPropertyChanged("DateTimeValidated");
					this.OnDateTimeValidatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Barcode_BarcodeFile", Storage="_Barcode", ThisKey="BarcodeId", OtherKey="Id", IsForeignKey=true)]
		public Barcode Barcode
		{
			get
			{
				return this._Barcode.Entity;
			}
			set
			{
				Barcode previousValue = this._Barcode.Entity;
				if (((previousValue != value) 
							|| (this._Barcode.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Barcode.Entity = null;
						previousValue.BarcodeFiles.Remove(this);
					}
					this._Barcode.Entity = value;
					if ((value != null))
					{
						value.BarcodeFiles.Add(this);
						this._BarcodeId = value.Id;
					}
					else
					{
						this._BarcodeId = default(int);
					}
					this.SendPropertyChanged("Barcode");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Barcodes")]
	public partial class Barcode : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _UserJobPlateId;
		
		private System.Nullable<int> _SubPlateId;
		
		private System.Nullable<int> _PrimerId;
		
		private string _StageId;
		
		private System.Nullable<int> _SourceBarcodeId;
		
		private System.Nullable<System.DateTime> _DateCreated;
		
		private System.Nullable<bool> _Done;
		
		private EntitySet<BarcodeFile> _BarcodeFiles;
		
		private EntitySet<Barcode> _Barcodes;
		
		private EntityRef<Barcode> _Barcode1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnUserJobPlateIdChanging(System.Nullable<int> value);
    partial void OnUserJobPlateIdChanged();
    partial void OnSubPlateIdChanging(System.Nullable<int> value);
    partial void OnSubPlateIdChanged();
    partial void OnPrimerIdChanging(System.Nullable<int> value);
    partial void OnPrimerIdChanged();
    partial void OnStageIdChanging(string value);
    partial void OnStageIdChanged();
    partial void OnSourceBarcodeIdChanging(System.Nullable<int> value);
    partial void OnSourceBarcodeIdChanged();
    partial void OnDateCreatedChanging(System.Nullable<System.DateTime> value);
    partial void OnDateCreatedChanged();
    partial void OnDoneChanging(System.Nullable<bool> value);
    partial void OnDoneChanged();
    #endregion
		
		public Barcode()
		{
			this._BarcodeFiles = new EntitySet<BarcodeFile>(new Action<BarcodeFile>(this.attach_BarcodeFiles), new Action<BarcodeFile>(this.detach_BarcodeFiles));
			this._Barcodes = new EntitySet<Barcode>(new Action<Barcode>(this.attach_Barcodes), new Action<Barcode>(this.detach_Barcodes));
			this._Barcode1 = default(EntityRef<Barcode>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserJobPlateId", DbType="Int")]
		public System.Nullable<int> UserJobPlateId
		{
			get
			{
				return this._UserJobPlateId;
			}
			set
			{
				if ((this._UserJobPlateId != value))
				{
					this.OnUserJobPlateIdChanging(value);
					this.SendPropertyChanging();
					this._UserJobPlateId = value;
					this.SendPropertyChanged("UserJobPlateId");
					this.OnUserJobPlateIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubPlateId", DbType="Int")]
		public System.Nullable<int> SubPlateId
		{
			get
			{
				return this._SubPlateId;
			}
			set
			{
				if ((this._SubPlateId != value))
				{
					this.OnSubPlateIdChanging(value);
					this.SendPropertyChanging();
					this._SubPlateId = value;
					this.SendPropertyChanged("SubPlateId");
					this.OnSubPlateIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrimerId", DbType="Int")]
		public System.Nullable<int> PrimerId
		{
			get
			{
				return this._PrimerId;
			}
			set
			{
				if ((this._PrimerId != value))
				{
					this.OnPrimerIdChanging(value);
					this.SendPropertyChanging();
					this._PrimerId = value;
					this.SendPropertyChanged("PrimerId");
					this.OnPrimerIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StageId", DbType="Char(4)")]
		public string StageId
		{
			get
			{
				return this._StageId;
			}
			set
			{
				if ((this._StageId != value))
				{
					this.OnStageIdChanging(value);
					this.SendPropertyChanging();
					this._StageId = value;
					this.SendPropertyChanged("StageId");
					this.OnStageIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SourceBarcodeId", DbType="Int")]
		public System.Nullable<int> SourceBarcodeId
		{
			get
			{
				return this._SourceBarcodeId;
			}
			set
			{
				if ((this._SourceBarcodeId != value))
				{
					if (this._Barcode1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSourceBarcodeIdChanging(value);
					this.SendPropertyChanging();
					this._SourceBarcodeId = value;
					this.SendPropertyChanged("SourceBarcodeId");
					this.OnSourceBarcodeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateCreated", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateCreated
		{
			get
			{
				return this._DateCreated;
			}
			set
			{
				if ((this._DateCreated != value))
				{
					this.OnDateCreatedChanging(value);
					this.SendPropertyChanging();
					this._DateCreated = value;
					this.SendPropertyChanged("DateCreated");
					this.OnDateCreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Done", DbType="Bit")]
		public System.Nullable<bool> Done
		{
			get
			{
				return this._Done;
			}
			set
			{
				if ((this._Done != value))
				{
					this.OnDoneChanging(value);
					this.SendPropertyChanging();
					this._Done = value;
					this.SendPropertyChanged("Done");
					this.OnDoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Barcode_BarcodeFile", Storage="_BarcodeFiles", ThisKey="Id", OtherKey="BarcodeId")]
		public EntitySet<BarcodeFile> BarcodeFiles
		{
			get
			{
				return this._BarcodeFiles;
			}
			set
			{
				this._BarcodeFiles.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Barcode_Barcode", Storage="_Barcodes", ThisKey="Id", OtherKey="SourceBarcodeId")]
		public EntitySet<Barcode> Barcodes
		{
			get
			{
				return this._Barcodes;
			}
			set
			{
				this._Barcodes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Barcode_Barcode", Storage="_Barcode1", ThisKey="SourceBarcodeId", OtherKey="Id", IsForeignKey=true)]
		public Barcode Barcode1
		{
			get
			{
				return this._Barcode1.Entity;
			}
			set
			{
				Barcode previousValue = this._Barcode1.Entity;
				if (((previousValue != value) 
							|| (this._Barcode1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Barcode1.Entity = null;
						previousValue.Barcodes.Remove(this);
					}
					this._Barcode1.Entity = value;
					if ((value != null))
					{
						value.Barcodes.Add(this);
						this._SourceBarcodeId = value.Id;
					}
					else
					{
						this._SourceBarcodeId = default(Nullable<int>);
					}
					this.SendPropertyChanged("Barcode1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BarcodeFiles(BarcodeFile entity)
		{
			this.SendPropertyChanging();
			entity.Barcode = this;
		}
		
		private void detach_BarcodeFiles(BarcodeFile entity)
		{
			this.SendPropertyChanging();
			entity.Barcode = null;
		}
		
		private void attach_Barcodes(Barcode entity)
		{
			this.SendPropertyChanging();
			entity.Barcode1 = this;
		}
		
		private void detach_Barcodes(Barcode entity)
		{
			this.SendPropertyChanging();
			entity.Barcode1 = null;
		}
	}
}
#pragma warning restore 1591
