#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAESGenome.Console
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="cgf")]
	public partial class DataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBarcodeFile(BarcodeFile instance);
    partial void UpdateBarcodeFile(BarcodeFile instance);
    partial void DeleteBarcodeFile(BarcodeFile instance);
    #endregion
		
		public DataDataContext() : 
				base(global::CAESGenome.Console.Properties.Settings.Default.cgfConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<BarcodeFile> BarcodeFiles
		{
			get
			{
				return this.GetTable<BarcodeFile>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BarcodeFiles")]
	public partial class BarcodeFile : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _WellColumn;
		
		private char _WellRow;
		
		private int _BarcodeId;
		
		private bool _Uploaded;
		
		private bool _Validated;
		
		private System.Nullable<int> _Start;
		
		private System.Nullable<int> _End;
		
		private System.DateTime _DateTimeUploaded;
		
		private System.Nullable<System.DateTime> _DateTimeValidated;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnWellColumnChanging(int value);
    partial void OnWellColumnChanged();
    partial void OnWellRowChanging(char value);
    partial void OnWellRowChanged();
    partial void OnBarcodeIdChanging(int value);
    partial void OnBarcodeIdChanged();
    partial void OnUploadedChanging(bool value);
    partial void OnUploadedChanged();
    partial void OnValidatedChanging(bool value);
    partial void OnValidatedChanged();
    partial void OnStartChanging(System.Nullable<int> value);
    partial void OnStartChanged();
    partial void OnEndChanging(System.Nullable<int> value);
    partial void OnEndChanged();
    partial void OnDateTimeUploadedChanging(System.DateTime value);
    partial void OnDateTimeUploadedChanged();
    partial void OnDateTimeValidatedChanging(System.Nullable<System.DateTime> value);
    partial void OnDateTimeValidatedChanged();
    #endregion
		
		public BarcodeFile()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WellColumn", DbType="Int NOT NULL")]
		public int WellColumn
		{
			get
			{
				return this._WellColumn;
			}
			set
			{
				if ((this._WellColumn != value))
				{
					this.OnWellColumnChanging(value);
					this.SendPropertyChanging();
					this._WellColumn = value;
					this.SendPropertyChanged("WellColumn");
					this.OnWellColumnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WellRow", DbType="Char(1) NOT NULL")]
		public char WellRow
		{
			get
			{
				return this._WellRow;
			}
			set
			{
				if ((this._WellRow != value))
				{
					this.OnWellRowChanging(value);
					this.SendPropertyChanging();
					this._WellRow = value;
					this.SendPropertyChanged("WellRow");
					this.OnWellRowChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BarcodeId", DbType="Int NOT NULL")]
		public int BarcodeId
		{
			get
			{
				return this._BarcodeId;
			}
			set
			{
				if ((this._BarcodeId != value))
				{
					this.OnBarcodeIdChanging(value);
					this.SendPropertyChanging();
					this._BarcodeId = value;
					this.SendPropertyChanged("BarcodeId");
					this.OnBarcodeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Uploaded", DbType="Bit NOT NULL")]
		public bool Uploaded
		{
			get
			{
				return this._Uploaded;
			}
			set
			{
				if ((this._Uploaded != value))
				{
					this.OnUploadedChanging(value);
					this.SendPropertyChanging();
					this._Uploaded = value;
					this.SendPropertyChanged("Uploaded");
					this.OnUploadedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Validated", DbType="Bit NOT NULL")]
		public bool Validated
		{
			get
			{
				return this._Validated;
			}
			set
			{
				if ((this._Validated != value))
				{
					this.OnValidatedChanging(value);
					this.SendPropertyChanging();
					this._Validated = value;
					this.SendPropertyChanged("Validated");
					this.OnValidatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Start", DbType="Int")]
		public System.Nullable<int> Start
		{
			get
			{
				return this._Start;
			}
			set
			{
				if ((this._Start != value))
				{
					this.OnStartChanging(value);
					this.SendPropertyChanging();
					this._Start = value;
					this.SendPropertyChanged("Start");
					this.OnStartChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[End]", Storage="_End", DbType="Int")]
		public System.Nullable<int> End
		{
			get
			{
				return this._End;
			}
			set
			{
				if ((this._End != value))
				{
					this.OnEndChanging(value);
					this.SendPropertyChanging();
					this._End = value;
					this.SendPropertyChanged("End");
					this.OnEndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateTimeUploaded", DbType="DateTime2 NOT NULL")]
		public System.DateTime DateTimeUploaded
		{
			get
			{
				return this._DateTimeUploaded;
			}
			set
			{
				if ((this._DateTimeUploaded != value))
				{
					this.OnDateTimeUploadedChanging(value);
					this.SendPropertyChanging();
					this._DateTimeUploaded = value;
					this.SendPropertyChanged("DateTimeUploaded");
					this.OnDateTimeUploadedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateTimeValidated", DbType="DateTime2")]
		public System.Nullable<System.DateTime> DateTimeValidated
		{
			get
			{
				return this._DateTimeValidated;
			}
			set
			{
				if ((this._DateTimeValidated != value))
				{
					this.OnDateTimeValidatedChanging(value);
					this.SendPropertyChanging();
					this._DateTimeValidated = value;
					this.SendPropertyChanged("DateTimeValidated");
					this.OnDateTimeValidatedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
